name: tripduu
description: A new Flutter project.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_mobx: ^2.0.0
  mobx: ^2.0.1
  flutter_modular: ^3.1.1+1




  

dev_dependencies:
  build_runner: ^2.0.5
  mobx_codegen: ^2.0.1+3
  sentry_flutter: ^6.5.1


  flutter_test:
    sdk: flutter
  
flutter:
  uses-material-design: true
  # assets: 
  #  - assets/icons/
  # fonts:
  #   - family: Lato
  #     fonts:
  #       - asset: assets/fonts/Lato-Bold.ttf
  #         weight: 700
  #       - asset: assets/fonts/Lato-Regular.ttf
  #         weight: 400    




